INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('﻿Piece of wood', '1.1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron piece', '2.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Stone piece', '1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mulberry leaf', '0.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hay', '0.95');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Clay piece', '1.2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Bread', '0.7');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Jar of milk', '0.78');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wheat bag', '0.85');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Paper piece', '0.6');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mulberry', '1.4');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Herbs and Honey infusion', '7.4');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Bricks', '2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Salt heap', '1.44');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Meat', '2.85');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wheat seed', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Coal piece', '2.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Manure', '1.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Fertilizer', '2.2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Leather piece', '2.8');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Pottery', '2.3');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Cheese', '8');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mulberry seed', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Linen seed', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Medical herbs', '1.3');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Sand heap', '2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Linen yarn', '1.9');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Meat soup', '11');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Cotton yarn', '2.2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wax piece', '1.1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Glass bottle', '1.1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Flowers', '1.2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wool yarn', '3');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Cotton seed', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Honey', '3.4');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Medical herb seed', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Medicinal mushrooms', '1.8');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Fish', '3.6');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Fish soup', '111');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wax seal', '2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Silk yarn', '8');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Water bottle', '1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Flower seed', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hops', '0.3');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Grapes', '1.7');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mead bottle', '6');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wooden token', '1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Rag shirt', '5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Rag trousers', '5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Grape seed', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mulberry cake', '6.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Glass bulb', '5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hand axe', '30');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hammer', '12');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Male shoes', '20');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mulberry brandy', '12');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Longsword', '95');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Male short sleeve shirt', '35');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Gold piece', '10');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('War axe', '39.8');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wine bottle', '5.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Boots', '25');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hoe', '32');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Chainmail', '90.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Pickaxe', '36');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Male hose', '32');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Beer', '5.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hop seeds', '0.15');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wooden dummy', '14.1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Malt', '0.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron helmet mod 2', '60');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Shovel', '18');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Light leather armor', '41');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Leather trousers', '30');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Plate armor', '147');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Knife', '25');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mandragora', '1.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Violet potion', '50');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron sabatons', '31');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron leg armor', '97.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron bucket', '30.1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Short sword', '25.7');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Female shoes', '24.2');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron helmet mod 1', '14.7');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Robe', '65');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Strong leather trousers', '36');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron norman shield', '103');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Rag robe', '6');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wooden norman shield', '39.3');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Warhammer', '66.4');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hoe blade', '14.1');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Iron shield', '44.6');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Scimitar', '46.8');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Pickaxe hardhead', '25.9');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Fishing net', '49.8');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Halberd', '94');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Medium sized cart', '300');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hatchet blade', '15.4');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Bellow', '22.05');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Stripped male hose', '42');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Noblewoman''s gown', '130');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mace', '52');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Knife blade', '18');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Sapphire ring', '52');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wooden shield', '20');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Jar tar', '2000');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Male short sleeve shirt', '35');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Wooden barrel', '35');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Emerald ring', '52');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Bracelet', '93');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Press for grapes', '16');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Distiller', '27');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Morning star', '78');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Male hat', '35');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Ruby ring', '52');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Fauchard', '26');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Female hose', '322');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Female short sleeve shirt', '35');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Golden basin', '200');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Hood', '41');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Female hat', '35');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Veil', '180');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Small cart', '200');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Diamond ring', '2000');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Large jar', '160');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Crown', '2000');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Female stripped hose', '42');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Female long sleeve shirt', '160');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Sturdy table', '700');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Scissors', '13');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Saw', '14');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Potter tools', '11');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Sickle', '21');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Ink bulb', '65');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mandragora brew', '3.5');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Surgical kit', '5.84');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Surgical instruments', '4.4');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Health care kit', '14');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Holy book', '150');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Religious scepter', '102');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Mortar and pestle', '18');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Cooking pot', '20');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Male long sleeve shirt', '160');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Religious headpiece', '420');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Religious tunic lvl4', '223');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Religious tunic lvl3', '234');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Religious tunic lvl2', '234');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Religious tunic lvl1', '250');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Working hour', '3');
INSERT INTO sif_res(NAZIV, MON_VAL) VALUES ('Silver', '1');
